Dump info
meilisearch/MeiliSearch pull request #1008
Opened 2020-10-13 09:18 UTC by LegendreM

fix #998 
fix #988

2020-10-13 12:11 UTC, eskombro commented on meilisearch-http/src/option.rs
>      #[structopt(long, requires = "snapshot-path", env = "MEILI_SNAPSHOT_INTERVAL_SEC")]
snapshot-path seems to have changed to snapshot-dir, not sure. Can youy check please? :)

2020-10-13 14:59 UTC, eskombro commented on meilisearch-http/src/option.rs
>      #[structopt(long, requires = "snapshot-path", env = "MEILI_SNAPSHOT_INTERVAL_SEC")]
Otherwise, averything LGTM! 🎉

2020-10-15 11:07 UTC, eskombro commented on meilisearch-http/src/option.rs
>      #[structopt(long, requires = "snapshot-path", env = "MEILI_SNAPSHOT_INTERVAL_SEC")]
I mean L116 in the `requires`

2020-10-15 11:09 UTC, eskombro commented on meilisearch-http/src/option.rs
>      #[structopt(long, requires = "snapshot-path", env = "MEILI_SNAPSHOT_INTERVAL_SEC")]
Oh it is fixed, thanks! :)

2020-10-22 10:44 UTC, Kerollmops requested changes

2020-10-22 10:44 UTC, Kerollmops commented on meilisearch-http/tests/documents_add.rs
> +        "text":" The locations block is the most powerful, and potentially most involved, section of the .platform.app.yaml file. It allows you to control how the application container responds to in
Your sed/vscode find and replace, touched this line, and it should not had done that. sori.

2020-10-22 13:31 UTC, Kerollmops approved these changes
bors r+

2020-10-22 13:46 UTC, Kerollmops commented
bors r+

2020-10-22 14:23 UTC, Kerollmops approved these changes
bors r+

2020-10-22 14:47 UTC, merged