normalize synonyms during indexation
meilisearch/MeiliSearch pull request #1184
Opened 2021-01-12 12:56 UTC by LegendreM

fix #1135 #964

2021-01-13 09:45 UTC, LegendreM commented
bors try

2021-01-13 10:45 UTC, MarinPostma requested changes

2021-01-13 10:45 UTC, MarinPostma commented on meilisearch-core/src/update/settings_update.rs
> +            })
```suggestion
            .fold(String::new(), |mut s, t| s + t.text())
```

2021-01-13 12:17 UTC, LegendreM commented
bors try

2021-01-28 09:04 UTC, MarinPostma requested changes

2021-01-28 09:04 UTC, MarinPostma commented on meilisearch-core/src/update/settings_update.rs
> +            .fold(String::new(), |mut s, t| s + t.text())
```suggestion
            .fold(String::new(), |s, t| s + t.text())
```

2021-01-28 14:31 UTC, qdequele commented
@LegendreM How Chinese synonyms are handled? Are they also deunidecoded? What about emojis and others?

2021-02-01 10:58 UTC, qdequele commented
> @LegendreM How Chinese synonyms are handled? Are they also deunidecoded? What about emojis and others?

After a discussion with @LegendreM, the only Latin based languages will be normalized.

2021-02-01 12:27 UTC, LegendreM commented
bors merge

2021-02-01 13:25 UTC, MarinPostma approved these changes

2021-02-01 14:43 UTC, merged