Use 200 status code for healthcheck endpoint
meilisearch/MeiliSearch pull request #1291
Opened 2021-03-16 10:19 UTC by irevoire

closes  #1282

2021-03-16 12:26 UTC, curquiza requested changes
Thanks for your PR!

Could you please replace "status: ok" by "status: available"? We chose to follow the IBM convention -> https://github.com/meilisearch/MeiliSearch/issues/1282#issuecomment-799424875

2021-03-17 13:10 UTC, curquiza approved these changes

2021-03-18 06:07 UTC, MarinPostma requested changes

2021-03-18 06:07 UTC, MarinPostma commented on meilisearch-http/src/routes/health.rs
> +    Ok(HttpResponse::Ok().body(payload.to_string()))
Can you change to use the json method please?

2021-03-18 11:02 UTC, MarinPostma approved these changes
Lgtm

2021-03-18 11:02 UTC, MarinPostma commented
bors merge

2021-03-18 11:34 UTC, merged