Remove mods
meilisearch/MeiliSearch pull request #1669
Opened 2021-09-06 08:36 UTC by ManyTheFish

2021-09-06 12:24 UTC, Kerollmops commented
We should [open an issue](https://github.com/GuillaumeGomez/sysinfo/issues) to inform @GuillaumeGomez of that issue. It seems to be related to [the `total_memory_bytes` function and on Windows only](https://github.com/meilisearch/MeiliSearch/blob/33514b28be4fcace8dfd77f75abec3aca9a9d5c9/meilisearch-http/src/option.rs#L289-L299).

We could use [a `cfg` for windows only](https://doc.rust-lang.org/rust-by-example/attribute/cfg.html) that use `None` instead of trying to get the total memory.

2021-09-06 12:28 UTC, GuillaumeGomez commented
What's the issue exactly?

2021-09-06 12:45 UTC, Kerollmops commented
Hey @GuillaumeGomez,

Sorry for pinging you, maybe it's a little bit early but we [have a `STATUS_ACCESS_VIOLATION`](https://github.com/meilisearch/MeiliSearch/runs/3524069020?check_suite_focus=true#step:5:285) on windows when executing our tests on windows. But, I would like to ping you back when we are sure it is not just related to our memory consumption. I didn't found much information about this error and when it is raised on the internet.

Sorry for that ❤️

2021-09-06 12:47 UTC, GuillaumeGomez commented
I see, no problem. Well, feel free to send a PR or a more complete explanation on how to reproduce it locally. ;)

2021-09-07 07:59 UTC, curquiza requested changes
⚠️ The branch should point to `release-v0.22.0`

2021-09-08 09:10 UTC, ManyTheFish commented
Hey @GuillaumeGomez, no issue on your side, we had excessive memory consumption.
Thanks for your quick response!

2021-09-08 12:44 UTC, MarinPostma approved these changes
thanks you!!

bors merge

2021-09-08 13:18 UTC, merged