Make exec binary for M1 mac available for download
meilisearch/MeiliSearch pull request #1697
Opened 2021-09-11 14:23 UTC by k-nasa

## Why

fix: https://github.com/meilisearch/MeiliSearch/issues/1661

Now, Do not supported getting exec file for m1 mac on using`download-latest.sh`.

## What

Download x86 binary when run `download-latest.sh` on m1 mac, because it can execute binary targeting x86.

## Proof

I verified like this.
I got executable binary on M1 mac 💡 

```sh
:) % arch
arm64

:) % ./download-latest.sh
Downloading MeiliSearch binary v0.21.1 for macos, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   631  100   631    0     0   2035      0 --:--:-- --:--:-- --:--:--  2035
100 43.5M  100 43.5M    0     0  7826k      0  0:00:05  0:00:05 --:--:-- 9123k
MeiliSearch binary successfully downloaded as 'meilisearch' file.

Run it:
    $ ./meilisearch
Usage:
    $ ./meilisearch --help

:) % file ./meilisearch
./meilisearch: Mach-O 64-bit executable x86_64

:) % ./meilisearch --help # this is execuable
meilisearch-http 0.21.1
...
...
```

2021-09-11 23:04 UTC, irevoire commented
This looks good to me

2021-09-13 08:38 UTC, curquiza commented
Hello @k-nasa, thanks for your PR, I look this as soon as possible :)

2021-09-13 08:57 UTC, irevoire commented
Tested it on my M1 and it works. 
@curquiza I think we can merge 😄

2021-09-13 12:42 UTC, curquiza requested changes

2021-09-13 12:42 UTC, curquiza commented on download-latest.sh
> +    'x86_64' | 'amd64' | 'arm64')
I would rather download the armv8 binary for the M1 :) If a machine has an `arm64` architecture and is not a M1, it will not work.

2021-09-13 12:42 UTC, curquiza commented on download-latest.sh
> +    'x86_64' | 'amd64' | 'arm64')
```suggestion
    'x86_64' | 'amd64')
```

2021-09-13 12:42 UTC, curquiza commented on download-latest.sh
>      'aarch64')
```suggestion
    'aarch64' | 'arm64')
```

2021-09-19 14:47 UTC, k-nasa commented
I fixed it 🙏

2021-09-20 08:56 UTC, irevoire commented
Hello @k-nasa I tried this version on my M1 mac and this is what I got 🥺 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/7032172/133977828-739597f4-b566-4b6b-98f4-7210a817bfc1.png">

2021-09-20 11:48 UTC, k-nasa commented
Oops...  I overlooked to lack arm binary on macos.

How about solving it with the following steps?

1. Download x86 binary for macos aarch64 (this pr) It should be better than the current undownloadable situation.
2. Release macos aarch64 binary
3. Update the script and download aarch64

2021-09-20 11:56 UTC, k-nasa commented
ref: https://github.com/actions/virtual-environments/issues/2187

> 2. Release macos aarch64 binary

If i try to do this with actions, you may need to devise.

2021-09-20 11:57 UTC, irevoire commented
I think we can't build macOS Aarch64 binary with github action, so it would probably be better to stay with option 1:
> Download the macos x86 binary for macos aarch64

2021-09-20 12:01 UTC, k-nasa commented
🆗  If so, I think it is made of this PR.
I checked locally and found that x86 binary could be executed.

2021-09-20 12:30 UTC, irevoire commented
Yes now it work like a charm!
![image](https://user-images.githubusercontent.com/7032172/134000299-4c9bd007-2444-416f-93c8-b9ea508f27e8.png)

Do you know if this PR would work on a raspberry pi for example? (A linux armv8)

2021-09-30 09:43 UTC, MarinPostma commented
@irevoire what's the status of this pr?

2021-09-30 09:49 UTC, irevoire commented
I think we can merge, the day someone will try to use this script with a raspberry-pi, if it doesn't works he'll submit a new issue :grimacing:

2021-09-30 10:36 UTC, MarinPostma approved these changes
thank you for your contribution :)

bors merge

2021-09-30 11:33 UTC, irevoire approved these changes
bors merge

2021-09-30 11:48 UTC, merged

2021-10-01 00:42 UTC, k-nasa commented
Thanks for review ❤️