Reintroduce engine version file
meilisearch/MeiliSearch pull request #1860
Opened 2021-10-30 08:33 UTC by mbStavola

Right now if you boot up MeiliSearch and point it to a DB directory created with a previous version of MeiliSearch the existing indexes will be deleted. This [used to be](https://github.com/meilisearch/MeiliSearch/commit/51d7c84e7327b14f84522a1f5521f6d98c398a6f) prevented by a startup check which would compare the current engine version vs what was stored in the DB directory's version file, but this functionality seems to have been lost after a few refactorings of the code.

In order to go back to the old behavior we'll need to reintroduce the `VERSION` file that used to be present; I considered reusing the `metadata.json` file used in the dumps feature, but this seemed like the simpler and more approach. As the intent is just to restore functionality, the implementation is quite basic. I imagine that in the future we could build on this and do things like compatibility across major/minor versions and even migrating between formats.

Closes #1840

2021-11-02 19:10 UTC, curquiza commented
Hello @mbStavola thanks for your PR
We need to discuss with the team how we want to solve this properly. We'll come back to you! 🙂

2021-11-15 14:25 UTC, irevoire requested changes
Hello @mbStavola, we finished debating on how we want to implement this and we decided to accept your PR.
There is quite a lot of changes. So if you realize you don’t have the time or don’t want to finish this PR please let me know and I will take care of fixing everything. 😁 

We’ll also improve our process to better follow when we break our database because currently, we don’t really know.

I also noticed that the VERSION file was not read or written when importing a [snapshot](https://docs.meilisearch.com/reference/features/snapshots.html).

2021-11-16 19:15 UTC, mbStavola commented
@irevoire I'm definitely interested in following through and the changes suggested seem relatively minor. Please note, it might take me a day or two to get back to this, so use your best judgement/sense of urgency to determine if you'd like for me to finish this up or not.

2021-11-16 19:23 UTC, irevoire commented
Yeeoos thank you 🎉 
I don’t really know if we are in a hurry for this PR. What do you think @curquiza?

2021-11-17 10:05 UTC, curquiza commented
We need this bug not to be present in the next version (v0.25.0) -> the pre-release is December 6th :) According to this date, if you don't have the time @mbStavola (we would completely understand), @irevoire will need to take your branch and continue your work :)
Is it ok for you @irevoire and @mbStavola?

2021-11-18 09:09 UTC, CaroFG commented on meilisearch-lib/src/index_controller/versioning/error.rs
> +    #[error("Version file is missing")]
"its database"

2021-12-02 14:29 UTC, irevoire commented
Hello @mbStavola we do not have much time left before the release so I'm going to take back this PR.
I'm going to cherry-pick your commits so you'll still be listed as a contributor, thanks for your contribution! :tada:

2021-12-02 16:30 UTC, irevoire commented
Closing this PR in favor of  #1965

2021-12-02 16:30 UTC, closed without merging

2021-12-02 18:54 UTC, mbStavola commented
@irevoire Sorry! This was a bit of a miscommunication, when I reacted to @curquiza 's comment it was to signify that I was okay handing it off since you had a deadline you wanted to meet. In retrospect a direct comment would've been better 😅

Apologies for any confusion!

2021-12-02 21:54 UTC, irevoire commented
No problem 👍