Dumpv4
meilisearch/MeiliSearch pull request #1961
Opened 2021-12-01 19:50 UTC by irevoire

2021-12-01 20:36 UTC, MarinPostma requested changes

2021-12-01 20:36 UTC, MarinPostma commented on meilisearch-lib/src/update_file_store.rs
> +            println!("HERE1");
You forgot that

2021-12-02 02:05 UTC, irevoire commented on meilisearch-lib/src/update_file_store.rs
> +                println!("Reading: {}, {}", entry.path().display(), file_uuid);
```suggestion
```

2021-12-02 02:05 UTC, irevoire commented on meilisearch-lib/src/update_file_store.rs
> +            println!("HERE1");
```suggestion
```

2021-12-02 02:05 UTC, irevoire commented on meilisearch-lib/src/update_file_store.rs
> +            println!("HERE5");
```suggestion
            dst.push(&uuid_string);

            let update_file = File::open(update_file_path)?;
            let mut dst_file = NamedTempFile::new_in(&dump_path)?;
            let mut document_reader = DocumentBatchReader::from_reader(update_file)?;
```

2021-12-02 02:07 UTC, irevoire commented on meilisearch-lib/src/update_file_store.rs
> +            println!("HERE1");
```suggestion
```

2021-12-02 08:00 UTC, MarinPostma approved these changes

2021-12-02 08:01 UTC, merged