bug(http): fix task duration
meilisearch/MeiliSearch pull request #2066
Opened 2022-01-11 16:02 UTC by MarinPostma

@gmourrier found that the duration in the task view was not computed correctly, this pr fixes it.

@curquiza, I let you decide if we need to make a hotfix out of this or wait for the next release. This is not breaking.

2022-01-11 16:05 UTC, Kerollmops requested changes
Be careful, your commit seems anonymous or something. Maybe a missing email?

2022-01-12 00:31 UTC, irevoire approved these changes
:+1:

2022-01-12 14:48 UTC, curquiza commented
Not something that deserves a hotfix. If a bigger bug is reported, I will put this bug fix in the patch version as well :)
Let's merge this on `main` only for the moment

2022-01-12 14:48 UTC, curquiza approved these changes

2022-01-12 14:49 UTC, MarinPostma commented
Bors merge

2022-01-12 14:50 UTC, MarinPostma commented
bors merge

2022-01-12 15:14 UTC, merged