Fix #2107
meilisearch/meilisearch pull request #2207
Opened 2022-03-04 02:48 UTC by CNLHC

# Pull Request

> i will complete this PR later.

## What does this PR do?
Fixes #2107 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-03-07 09:37 UTC, Kerollmops requested changes
Thank you very much for your PR!
Apart from some esthetic changes, it's good for me.

2022-03-07 09:37 UTC, Kerollmops commented on meilisearch-lib/src/document_formats.rs
> +            },
```suggestion
            Self::Internal(e) => write!(f, "An internal error has occurred: `{}`.", e),
            Self::MalformedPayload(me, b) => match me.borrow() {
                milli::documents::Error::JsonError(se) => write!(
                    f,
                    "The `{}` payload provided is malformed. `Couldn't serialize document value at line {} column {}`",
                    b, se.line(), se.column()
                ),
                _ => write!(f, "The `{}` payload provided is malformed: `{}`.", b, me),
            },
```

2022-03-08 13:17 UTC, Kerollmops requested changes
I had some thoughts about your PR and think it removes too much information about the error, users will be lost if an error occurs and only the line and column are specified.

What do you think about ellipsing the message? By using something like 50 chars at the start and 50 chars at the end:
```
The `json` payload provided is malformed. `Couldn't serialize document value: invalid type: string \"my very ver...very very long body here\", expected a documents, or a sequence of documents. at line 1 column 7`.
```

2022-03-08 13:17 UTC, Kerollmops commented on meilisearch-lib/src/document_formats.rs
> +}
```suggestion
}

```

2022-03-08 13:17 UTC, Kerollmops commented on meilisearch-lib/src/document_formats.rs
> +impl std::error::Error for DocumentFormatError {}
```suggestion

impl std::error::Error for DocumentFormatError {}
```

2022-03-24 21:07 UTC, CNLHC commented
Sorry for the late response. I will submit a patch to  follow the suggestion of @Kerollmops today.

2022-03-28 13:42 UTC, curquiza commented
@CNLHC thanks a lot for these changes 🙏 
Looks like there is a tiny issue to fix with our clippy CI before Kero reviews it :)

2022-03-29 15:56 UTC, Kerollmops requested changes
Thank you very much for your contribution ❤️
However, could you modify the tests according to the changes I proposed with the ellipsing algorithm? And could you stash everything into one final commit when we are done, please?

2022-03-29 15:56 UTC, Kerollmops commented on meilisearch-http/tests/documents/add_documents.rs
> +    .unwrap();
```suggestion
    let long = "0123456789".repeat(10);
```

2022-03-31 02:24 UTC, CNLHC commented on meilisearch-lib/src/document_formats.rs
> +                )
In some cases, this method will lead to weird error messages. For example, if the raw message is 
```
The `json` payload provided is malformed. `Couldn't serialize document value: invalid type: string "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789", expected a documents, or a sequence of documents. at line 1 column 102`.
```

Using your method, ellipsing the string without parsing the context will  generate

```
The `json` payload provided is malformed. `Couldn't serialize document value: invalid type: string \"0123456789012345678901234567..., or a sequence of documents. at line 1 column 102`.
```

Some meaningful information(The `expected a documents`)  is truncated.

2022-03-31 02:30 UTC, CNLHC commented on meilisearch-lib/src/document_formats.rs
> +                )
The meaningful suffix length cannot be determined. But in most cases, its length is around `75` which is 
`", expected a documents, or a sequence of documents. at line <LINE_NUMBER> column <COLUMN_NUMBER>`

So I suggest to change  `50..serde_msg.len() - 50` to 50..serde_msg.len() - 85`

2022-03-31 15:21 UTC, Kerollmops requested changes
Thank you, that's better and clever. Could you remove the `dbg!` in the test and I'll merge after that, please?
Once you have done so, could you squash everything in one commit and rebase on main, please?

2022-03-31 15:21 UTC, Kerollmops commented on meilisearch-http/tests/documents/add_documents.rs
> +    dbg!(&response);
```suggestion
    let response: Value = serde_json::from_slice(&body).unwrap_or_default();
```

2022-03-31 15:21 UTC, Kerollmops commented on meilisearch-http/tests/documents/add_documents.rs
> +    dbg!(&response);
```suggestion
    let response: Value = serde_json::from_slice(&body).unwrap_or_default();
```

2022-04-01 01:30 UTC, CNLHC commented on meilisearch-http/tests/documents/add_documents.rs
> +    dbg!(&response);
Oh, It's my fault. I should remove it.

2022-04-04 17:23 UTC, Kerollmops approved these changes
Thank you very much for your work @CNLHC, merging now!
bors merge

2022-04-04 17:50 UTC, merged