Add test to validate cli
meilisearch/MeiliSearch pull request #2245
Opened 2022-03-16 16:25 UTC by MarinPostma

followup on #2242 and #2243

Add a test to make sure the cli is valid, and add a CI task to run the tests in debug to make sure we hit debug assertions.

FYI @curquiza, because of CI changes

2022-03-16 16:30 UTC, irevoire submitted a review, later dismissed
Good idea :+1:

2022-03-16 16:32 UTC, MarinPostma commented
will wait for #2243 to merge before, otherwise the CI will fail.

2022-03-16 19:20 UTC, curquiza requested changes
Good idea @MarinPostma!!!

Can we add the test to bors?

2022-03-16 19:42 UTC, curquiza approved these changes
👍

2022-03-17 07:10 UTC, MarinPostma commented
bors merge

2022-03-17 07:10 UTC, MarinPostma commented
bors cancel

2022-03-17 07:11 UTC, MarinPostma commented
I need to fix the new CI

2022-03-17 16:14 UTC, irevoire approved these changes
bors merge

2022-03-17 16:29 UTC, merged