Test with default cli opts
meilisearch/meilisearch pull request #2254
Opened 2022-03-21 10:02 UTC by Kerollmops

This PR makes sure that we test the HTTP engine with the default CLI parameters and removes some useless internal CLI options.

2022-03-21 10:20 UTC, MarinPostma commented
@Kerollmops tests are failing, clap seems to need a default implementation for IndexerOpts

2022-03-21 10:28 UTC, Kerollmops commented
Hum... I tested that on another branch where the `indexer_opts` argument is not skipped and it worked fine, obviously. I will implement `Default` on this struct again as I removed the problematic options and it looks safe now.

2022-03-21 10:50 UTC, MarinPostma commented
@Kerollmops I have concerns that this will break windows tests: we need 100gib map for each running test thread

2022-03-21 10:59 UTC, Kerollmops commented
Wat do you mean? I kept the `max_index_size` limits here.

2022-03-21 11:04 UTC, MarinPostma commented
my bad! test still failed with OOM though

2022-03-22 09:18 UTC, ManyTheFish requested changes

2022-03-22 09:18 UTC, ManyTheFish commented on meilisearch-lib/src/options.rs
> +        IndexerOpts {
Why did you choose to explicitly specify the name?

2022-03-28 13:56 UTC, ManyTheFish approved these changes

2022-03-29 17:13 UTC, Kerollmops commented
We need to rebase this branch on #2280 to avoid this issue with lindera.

2022-03-29 18:37 UTC, Kerollmops commented
I just rebased on #2280, you can re-review this PR and we will be able to merge as the CI should compile now.

2022-03-29 19:55 UTC, MarinPostma approved these changes
Thanks @Kerollmops ! Happy to be able to merge that now 😁

2022-03-29 22:39 UTC, Kerollmops commented
Thank you!
bors merge

2022-03-29 23:00 UTC, merged