Update the tasks endpoints
meilisearch/meilisearch pull request #2399
Opened 2022-05-17 08:57 UTC by Kerollmops

This PR wraps all the changes related to the `tasks` endpoints, it will fix https://github.com/meilisearch/meilisearch/issues/2377.

We must merge this PR **once this list of PRs is merged** into this branch:

2022-05-30 09:00 UTC, MarinPostma requested changes

2022-05-30 09:00 UTC, MarinPostma commented on meilisearch-http/src/task.rs
> +    fn from_str(status: &str) -> Result<Self, String> {
Same here, I think we need to return a custom error.

2022-05-30 15:29 UTC, MarinPostma commented on meilisearch-http/src/routes/tasks.rs
> +    };
This is a lot of repeated code though, another alternative is to move the match inside the closure


```rust
if type_.is_some() || status.is_some() {
    filter.filter_fn(move || {
        let pass_type = match type_ {
            ...
       };
        let pass_status  = match status {
            ...
       };
       pass_status && pass_type
})
```

2022-05-30 15:33 UTC, Kerollmops commented on meilisearch-http/src/routes/tasks.rs
> +    };
That's a good and better idea, you are right, I'll try this. Thank you!

2022-05-31 09:39 UTC, MarinPostma commented on meilisearch-http/src/task.rs
> +}
ping @gmourier I'm thinking that since we are case insensitive on that, maybe we should also be on ranking rules?

2022-05-31 09:40 UTC, MarinPostma approved these changes
👌 

bors merge

2022-05-31 09:57 UTC, merged