Paginate the index resource
meilisearch/meilisearch pull request #2423
Opened 2022-05-24 09:36 UTC by irevoire

Fix #2373

2022-05-26 11:47 UTC, MarinPostma requested changes

2022-05-26 11:47 UTC, MarinPostma commented on meilisearch-http/src/routes/indexes/mod.rs
> +    })))
can we create a type for that? `IndexListView`

2022-05-31 15:21 UTC, MarinPostma submitted a review, later dismissed
bors merge

2022-05-31 15:48 UTC, Kerollmops commented
@MarinPostma do you have any clue about [what's happening here](https://github.com/meilisearch/meilisearch/runs/6673948825?check_suite_focus=true)?

2022-05-31 15:55 UTC, MarinPostma commented
@irevoire is dealing with that

2022-05-31 19:25 UTC, MarinPostma approved these changes
bors merge

2022-05-31 19:40 UTC, merged