Update docker volume path
meilisearch/meilisearch pull request #2434
Opened 2022-05-26 02:36 UTC by 0x0x1

Currently, the args `$(pwd)/data.ms:/data.ms` cannot share data from the container, makes docker volume same as the [Dockerfile](https://github.com/0x0x1/meilisearch/blob/67b6f4340aaea005471a0ad41c700bde1d88afe9/Dockerfile#L40) to fixing it.

2022-05-30 13:21 UTC, irevoire approved these changes
Ah yes, good catch!
@curquiza it looks good to me but I let you merge

2022-05-30 13:54 UTC, curquiza commented
@irevoire isn't it better with `-v $(pwd)/meili_data:/meili_data` instead?

2022-05-31 18:27 UTC, irevoire commented
Ah yes obviously :facepalm: 
That's why we changed the path initially!

2022-05-31 18:28 UTC, irevoire requested changes

2022-05-31 18:28 UTC, irevoire commented on README.md
> +docker run -p 7700:7700 -v "$(pwd)/data.ms:/meili_data/data.ms" getmeili/meilisearch
```suggestion
docker run -p 7700:7700 -v "$(pwd)/meili_data:/meili_data" getmeili/meilisearch
```

2022-06-01 10:29 UTC, curquiza approved these changes

2022-06-01 10:51 UTC, merged