Seek based tasks list
meilisearch/meilisearch pull request #2445
Opened 2022-05-31 09:57 UTC by Kerollmops

2022-06-01 15:27 UTC, MarinPostma approved these changes
I like it!

Bors merge

2022-06-02 09:05 UTC, ManyTheFish requested changes

2022-06-02 09:24 UTC, Kerollmops commented on meilisearch-lib/src/tasks/task.rs
> +pub type TaskId = u32;
Because we use `RoaringBitmaps` now to store the tasks ids. This is not a real issue as creating more that 2^32 tasks is a lot.

2022-06-02 09:28 UTC, ManyTheFish approved these changes
Nice!
bors merge

2022-06-02 10:25 UTC, Kerollmops commented
A non-sense crash, running bors again!
bors merge

2022-06-02 10:54 UTC, merged