Update milli 0.29
meilisearch/meilisearch pull request #2468
Opened 2022-06-06 13:57 UTC by ManyTheFish

- [ ] Update milli to 0.29
- [x] Integrate charabia
- [x] Set disabled_words to Settings::Reset when Index::exact_words returns None

2022-06-06 16:08 UTC, Kerollmops requested changes

2022-06-06 16:08 UTC, Kerollmops commented on meilisearch-lib/src/index/index.rs
> +        };
We are sure that it is a `Vec` here, right? And that it doesn't cost anything to construct a default one. Can we change this line a little bit? Just to be sure, for the future.

```suggestion
        let disabled_words = match self.exact_words(txn)? {
            Some(fst) => fst.into_stream().into_strs()?.into_iter().collect(),
            None => Vec::new(),
        };
```

2022-06-07 08:33 UTC, Kerollmops approved these changes
I love this PR, it makes the code much easier to read, thank you!

bors merge

2022-06-07 09:16 UTC, ManyTheFish commented
because windows wasn't ready for the `v0.29`, let's give it another chance.
bors merge

2022-06-07 11:14 UTC, ManyTheFish commented
Three times in a row. 🤔
It begins to be annoying. I will rebase.

2022-06-07 15:03 UTC, ManyTheFish commented
bors merge

2022-06-07 15:49 UTC, ManyTheFish commented
Seriously? snapshots now? Ok round 9000:
bors merge

2022-06-07 16:27 UTC, curquiza commented
bors merge

2022-06-08 09:08 UTC, irevoire submitted a review, later dismissed

2022-06-08 09:09 UTC, irevoire commented
bors merge

2022-06-08 09:28 UTC, curquiza commented
bors merge

2022-06-08 09:49 UTC, ManyTheFish commented
last try before investigating:
bors merge

2022-06-08 11:14 UTC, Kerollmops submitted a review, later dismissed

2022-06-08 11:16 UTC, ManyTheFish commented
please. 🤞 

bors merge

2022-06-08 13:57 UTC, Kerollmops approved these changes
incro :chocolatine: yable!
bors merge

2022-06-08 15:06 UTC, merged