Fix typos
meilisearch/meilisearch pull request #2789
Opened 2022-09-20 14:41 UTC by kianmeng

# Pull Request

## What does this PR do?

Found via `codespell -L crate,nam,hart`.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-09-21 08:51 UTC, Kerollmops requested changes

2022-09-21 08:51 UTC, Kerollmops commented on meilisearch-lib/src/dump/compat/v3.rs
> -        let event = TaskEvent::Succeded {
This is an enum variant that we want to keep that way as it must be compatible with the previous versions that have this typo.

2022-09-21 08:51 UTC, Kerollmops commented on meilisearch-lib/src/dump/compat/v4.rs
> -    Succeded {
Same here. Could you remove this typo, please?

2022-09-21 08:51 UTC, Kerollmops commented on meilisearch-lib/src/dump/compat/v4.rs
> -            TaskEvent::Succeded { result, timestamp } => {
And here. Could you keep this typo?

2022-09-22 13:55 UTC, curquiza commented
Hello @kianmeng 

Do you plan to participate in Hacktoberfest? We can wait for 1st October if you want to merge the PR so that you will have at least 1 contribution

2022-09-22 14:14 UTC, kianmeng commented
@curquiza Noted, but I'm not interested in Hacktoberfest, you can merge it now if you want. Thanks for the offering though. :smile:

2022-09-22 14:17 UTC, curquiza commented
Noted! @Kerollmops I let you merge once you ok with the PR!

2022-10-03 08:48 UTC, Kerollmops approved these changes
Thank you!
bors merge

2022-10-03 10:24 UTC, merged

2022-10-03 11:35 UTC, curquiza commented
Thank you for contributing to Meilisearch. If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some swag from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

2022-10-03 13:56 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: