docs: update internal CLI documentation
meilisearch/meilisearch pull request #2839
Opened 2022-10-03 14:42 UTC by jeertmans

# Pull Request

## Related issue
Fixes #2810

## What does this PR do?
- Make internal CLI documentation match the online one

## Remarks
- Scope is limited to `meilisearch/meilisearch-http/src/option.rs`, not the flattened structs: should I also take care of them?
- Could not find online docs for `enable_metrics_route`
- Max column width wrapping was done by hand, so may not be perfect
- I removed the links from the internal doc: should I put them back?

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

2022-10-04 08:21 UTC, dichotommy commented on meilisearch-http/src/option.rs
> +    /// Meilisearch currently supports four log levels, listed in order of increasing verbosity:
```suggestion
    /// Meilisearch currently supports five log levels, listed in order of increasing verbosity:
```

2022-10-04 08:30 UTC, jeertmans commented on meilisearch-http/src/option.rs
> +    /// Meilisearch currently supports four log levels, listed in order of increasing verbosity:
Indeed, didn't even catch this!

2022-10-04 17:00 UTC, curquiza commented
bors try

2022-10-05 08:39 UTC, jeertmans commented
Oups, seems like I should have called rustfmt @curquiza. It is now done :-)

2022-10-05 16:04 UTC, curquiza approved these changes
Thanks for the PR @jeertmans 

I requested some changes after discussing with @dichotommy: we think only the basic description is enough. Sorry the issue was not clear enough

Also, I think you missed some options like `HTTP_ADDR`, if I'm correct.

💡 Of course, you can apply my suggestions of change directly on this PR

Thanks again for the PR

2022-10-05 16:05 UTC, curquiza requested changes
Oops sorry I made a mistake: I approved instead of request changes 😂

2022-10-05 17:07 UTC, jeertmans commented
Yes, indeed, I missed some attributes @curquiza! I applied requested changes, and I added missing attributes.

I think structs `IndexerOpts` and `SchedulerConfig` also need to be updated, but maybe that should be subject to another PR? Otherwise, I can update the docs here too.

2022-10-06 13:15 UTC, jeertmans commented
I'm fine with one PR @curquiza ;-)

I just added the 3 missing docs.

2022-10-06 13:32 UTC, curquiza approved these changes
Good for me! thanks a lot @jeertmans for being such reactive

bors merge

2022-10-06 13:39 UTC, jeertmans commented
It was a pleasure @curquiza! Thank you for your reactivity on my PR(s), it's always nice for contributors to receive feedback!

2022-10-06 14:14 UTC, merged