Upgrade clap to 4.0
meilisearch/meilisearch pull request #2851
Opened 2022-10-04 13:57 UTC by choznerol

# Pull Request

## Related issue
Fixes #2847

## What does this PR do?
1. Upgrade clap to the latest version or 4.0 (4.0.9 as of today) by following the [migrating instruction](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating) from [4.0 changelog](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating)
2. Fix an `ArgGroup` typo that can only be caught after upgrading to 4.0 in 20a715e29ed17c5a76229c98fb31504ada873597

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-05 07:29 UTC, loiclec commented
Hi @choznerol 👋  I will let you know when https://github.com/meilisearch/meilisearch/pull/2847 is merged so you can go forward with it.

On a personal note, I am really happy that you picked this issue to contribute. It is good to have someone else looking through the breaking changes introduced by clap 4.0, so thank you :-)

2022-10-05 12:59 UTC, choznerol commented
> Hi @choznerol 👋 I will let you know when #2847 is merged so you can go forward with it.
> 
> On a personal note, I am really happy that you picked this issue to contribute. It is good to have someone else looking through the breaking changes introduced by clap 4.0, so thank you :-)

Thank you for creating an informative and actionable issue like #2846!

2022-10-06 07:43 UTC, loiclec commented
https://github.com/meilisearch/meilisearch/pull/2847 is merged :)

2022-10-10 12:58 UTC, loiclec requested changes
I was a bit surprised to see that there were typos in the `requires = "import-snapshot"` derive arguments. But after testing, it looks like the old version worked correctly anyway. I guess both forms were allowed in past `clap` versions.

Thanks for posting the diff in the `--help` output. Most of the changes don't bother me (I am a little bit sad to lose the colours). However, I do think it would be good to keep the same order of arguments (what do you think about it @gmourier ?)

This can be done by changing the following on line 66 of `option.rs`:
```diff
#[derive(Debug, Clone, Parser, Serialize, Deserialize)]
+ #[clap(version, next_display_order = None)]
- #[clap(version)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
pub struct Opt {
```

Otherwise, like you, I don't see what else needs to change following the migration guide of clap v4. Maybe @irevoire or @Kerollmops will spot something else :-)

2022-10-10 13:21 UTC, Kerollmops approved these changes
Indeed, it is a bit sad that we lost the color, but it looks good to me.
I just found the first line of the `--help` output a little bit empty but it is for another PR 😄

Thank you very much!

2022-10-10 14:58 UTC, choznerol commented
> I do think it would be good to keep the same order of arguments

Thanks for sharing `next_display_order ` and `display_order`, I didn't know they exist. I am not sure about the trade-off between maintaining the original ordering v.s. adding some `(next_)display_order` code. Please let me know about your preference because I can update in this PR if the former is prefered :)

2022-10-10 14:59 UTC, choznerol commented
> I just found the first line of the --help output a little bit empty 

@Kerollmops I had the same question and later realized this may be an expected v4 feature. From the [Polishing Help](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#highlights) or v4 changelog:

> name/version header was removed because we couldn't justify the space it occupied when
Usage already includes the name
> --version is available for showing the same thing (if the program has a version set)

2022-10-11 08:18 UTC, loiclec commented
@choznerol I think we'd prefer to keep the original ordering for now. Maybe at some point later, we'll want to reorganise the help message to show the most important options first, but it will be in a separate PR :-)

2022-10-14 08:56 UTC, choznerol commented
> @choznerol I think we'd prefer to keep the original ordering for now. Maybe at some point later, we'll want to reorganise the help message to show the most important options first, but it will be in a separate PR :-)

I added 5dafdd9 and the old order is back 🎉 

I updated the diff output in the PR description and now noticed another difference in `wrap_help`.

> * (help) Line wrapping of help is now behind the existing wrap_help feature flag, either enable it or hard code your wraps (#4258)

2022-10-17 10:08 UTC, loiclec approved these changes

2022-10-17 10:40 UTC, merged