Fix the dump date-import of the dumpv4
meilisearch/meilisearch pull request #3190
Opened 2022-12-05 17:14 UTC by irevoire

# Pull Request
After merging https://github.com/meilisearch/meilisearch/pull/3012 I realized that the tests on the date of the dump-v4 were still ignored, thus, I fixed them and then noticed #3012 wasn't working properly.

## Related issue
Fixes https://github.com/meilisearch/meilisearch/issues/2987 a second time

@funilrys since you wrote most of the code you might be interested, but don't feel obligated to review this code. 
Someone from the team will double-check it works :grin:

2022-12-05 17:40 UTC, curquiza commented
Thanks @irevoire for the fix! Since I don't want to miss this PR as part of the fix for #3012 I remove the `skip-changelog` label

Thanks again for following the job!

2022-12-05 18:01 UTC, funilrys submitted a review, later dismissed

2022-12-05 18:12 UTC, irevoire commented on dump/src/reader/v4/mod.rs
> +                    created_at = task.created_at();
Yes, actually, this time, the index creation was done synchronously, which means the important timing was the task creation date and not the `processed` time!

2022-12-06 08:57 UTC, dureuill requested changes
Thank you for the changes!

I know this is not something coming from this PR, but I'm wondering about the possible 2 calls to `now_utc` [on this line and the next](https://github.com/meilisearch/meilisearch/pull/3190/files#diff-5ca2c8d1bf39067c35add46adc13a9774d0442bd1bf597770a86f6deaa746a28R188).

This makes it so it is possible to have two distinct times, is that a problem?

If so we could hoist the call to a local variable and pass the resulting offset to both fields that might need it. IMO it is OK to make the call even if the value is not ultimately needed because we're not in a performance-sensitive part of the application (if you feel otherwise you could guard the call on having one of created_at or updated_at not be None).

If having two distinct times is intended, maybe we should specify so in a comment here?

What do you think?

2022-12-06 08:57 UTC, dureuill commented on dump/src/reader/v4/mod.rs
> +                // this task represent our `created_at`.
typo

```suggestion
                // this task represents our `created_at`.
```

2022-12-06 10:24 UTC, dureuill approved these changes
Thank you! Looks good to me!

2022-12-06 10:42 UTC, irevoire commented
bors merge

2022-12-06 11:03 UTC, merged

2022-12-30 12:57 UTC, amab8901 commented
Why do I keep getting these notifications all the time? 
![image](https://user-images.githubusercontent.com/83634595/210072507-dc319688-95c9-485f-aa9b-654fa768caa7.png)