Reject master keys that are less than 16 bytes and add `--generate-master-key` CLI option
meilisearch/meilisearch pull request #3274
Opened 2022-12-22 13:35 UTC by dureuill

# Pull Request

## Related issue
Fixes #3272 

## What does this PR do?

### User standpoint

---

- Adds a `--generate-master-key` CLI flag to generate a fresh Master Key and exit.

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 18 58" src="https://user-images.githubusercontent.com/41078892/209142778-eab52eeb-eaa8-409b-897a-c0d5728c8aaa.png">

---

(relevant fragment of the `--help` message)

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 19 40" src="https://user-images.githubusercontent.com/41078892/209142891-ebfa2ed6-f231-4f76-a3ae-b7542c7aef04.png">

---

- When `meilisearch` is started in the `development` environment and no Master Key has been provided, then the binary prints a warning before starting.

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 14 49" src="https://user-images.githubusercontent.com/41078892/209142158-54eba3b7-bf71-4f3f-8840-0600b13a1a9f.png">

---

- When `meilisearch` is started in the `development` environment and the provided Master Key is shorter than 16 bytes, then the binary prints a warning before starting.

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 15 58" src="https://user-images.githubusercontent.com/41078892/209142295-0209fe47-c03b-424f-a73f-cee9b633137a.png">

---

- When `meilisearch` is started in the `production` environment, and no Master Key is provided, the error message is altered to generate a fresh Master Key.

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 29 31" src="https://user-images.githubusercontent.com/41078892/209144924-74082e3d-361d-4f05-8374-248719ffa13e.png">

---

- When `meilisearch` is started in the `production` environment, and the provided Master Key is shorter than 16 bytes, then the binary exits with an error.

<img width="1351" alt="Capture d’écran 2022-12-22 à 14 29 46" src="https://user-images.githubusercontent.com/41078892/209144763-d8bf0b40-7081-4888-b659-5b155e5aa275.png">

---

This implements the solution B described here: https://github.com/meilisearch/product/discussions/538#discussioncomment-4391346 

### Implementation standpoint

- Add a new `meilisearch-auth::generate_master_key` function that uses a Cryptographic Random Number Generator (CRNG) to fill a vector of 32 bytes before encoding these bytes as base64
- Refactor the various check on the environment and secret key in the `print_resume` function so that similar checks are performed in a single location.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-12-26 09:34 UTC, dureuill commented on meilisearch/src/main.rs
> +            eprintln!("A Master Key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.");
Here we go, what do you think?
<img width="1351" alt="Capture d’écran 2022-12-26 à 10 34 08" src="https://user-images.githubusercontent.com/41078892/209532556-a241f3b7-85e8-42aa-9f94-8ced1b716dd6.png">

2022-12-26 09:35 UTC, dureuill commented on meilisearch/src/main.rs
> +            eprintln!("If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY={}", generate_master_key());
Done ☺️ 

<img width="1351" alt="Capture d’écran 2022-12-26 à 10 33 27" src="https://user-images.githubusercontent.com/41078892/209532607-9d3167db-e375-41ae-97e5-6a24640fea8f.png">

2022-12-26 13:30 UTC, brunoocasali commented on meilisearch/src/main.rs
> +            eprintln!("A Master Key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.");
Looks good to me!

2022-12-26 13:30 UTC, brunoocasali commented on meilisearch/src/main.rs
> +            eprintln!("If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY={}", generate_master_key());
Looks good to me!

2022-12-26 13:36 UTC, dureuill commented on meilisearch/src/main.rs
> +            eprintln!("A Master Key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.");
Thank you for your review ❤️

2023-01-02 15:12 UTC, irevoire commented on meilisearch-auth/src/lib.rs
> +    let mut csprng = OsRng;
```suggestion
    // We need to use a cryptographically-secure source of randomness. That's why we're using the OsRng; https://crates.io/crates/getrandom
    let mut csprng = OsRng;
```

2023-01-02 15:32 UTC, irevoire requested changes

2023-01-02 15:32 UTC, irevoire commented on meilisearch/src/option.rs
> +    #[clap(long)]
We should create an env var as well

2023-01-02 16:00 UTC, irevoire approved these changes
bors merge

2023-01-02 16:21 UTC, merged

2023-01-05 10:42 UTC, gmourier commented
Hey everyone! 

I took some time to think about it, and I wonder if we are confident about adding `--generate-master-key` and if it's really necessary.

1. From what I see, there is only one use case where it appears; in all other cases, Meilisearch suggests a master-key. Wouldn't it be simpler to suggest a master-key in this case, too (for consistency & simplicity purposes)? 

> "When meilisearch is started in the development environment and the provided Master Key is shorter than 16 bytes, then the binary prints a warning before starting."

![use-case](https://user-images.githubusercontent.com/41078892/209142295-0209fe47-c03b-424f-a73f-cee9b633137a.png)


2. If yes, do we need a `generate-master-key` option?
    2.1 This is an option that, when specified does not start Meilisearch (it would be the only one)
    2.2 My opinion is that if it's suggested it is more than enough to help the user.
    2.3 This is adding an option that would be immediately stabilized and documented.
    
(Sorry to be late 🙇‍♂️) Note: This is something that can be removed during RC.

WDYT?