Remove `--max-index-size` and `--max-task-db-size` flags
meilisearch/meilisearch pull request #3278
Opened 2022-12-26 13:15 UTC by dureuill

# Pull Request

## Related issue
Fixes #3231 

## What does this PR do?
- Remove `--max-index-size` and `--max-task-db-size` flags from the CLI, config file and environment variable
- Set the size of all indexes to **500GiB** and the size of the task DB to **10GiB**.  Reviewers might want to review these values carefully.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-12-27 09:05 UTC, dureuill commented
Update the index size to 400GiB to try and address the tests failing in Windows. 

Alternatives:

1. reduce size only if cfg windows (will do if 400GiB still triggers the issue)
2. limit test parallelism (at least under Windows)

2022-12-27 10:28 UTC, dureuill commented
New attempt with 200GiB for Windows, 500GiB for other OSes.

The issues under windows underline the necessity of providing another mechanism to handle mapsizes. My preference goes towards automatically resizing environments, but we need to think about how we want to do this because this cannot be fully transparent at the heed level: as MDB_MAP_FULL is returned inside of a transaction (after a call to put), one has to abort that transaction, resize the environment, and then attempt again that transaction. This is best handled at the milli or even meilisearch level. I'm unsure how to make sure we always handle that condition and restart the full transaction in that case, I'm afraid that manually handling each call to db/cursor::put in the code is going to cause us to miss some (or in the future after a refactor). Ideally when aborting a txn due to an error we'd remember if it was caused to the max mapsize being reached and we'd resize at this point, before attempting the txn again.

2022-12-27 13:27 UTC, dureuill commented
Still not OK even with 200GiB for Windows. Adjustments made in the tests seem to suggest a situation quite dire in the CI: https://github.com/meilisearch/meilisearch/pull/2476/files

2023-01-03 16:16 UTC, Kerollmops commented
> I'm not sure how to proceed.

The only thing I suggest is reducing the size of the indexes for Windows only.

The solution you were proposing about closing and reopening the index with a bigger max index size is great. We could try thinking about that or ask Howard for help on how we should proceed with LMDB running on Windows.

2023-01-04 09:07 UTC, dureuill commented
Since the Windows CI tests keep failing with strange JavaScript heap errors, I changed strategy:

- The options are removed from config, env variable and CLI, but not from the `Opt` struct
- The tests uses the options like before, allowing to keep the same values
- The values are set to 500GiB per index, 10GiB for the db task queue, for all OSes.

2023-01-04 15:49 UTC, Kerollmops requested changes
I like what you've done! Will merge just after this small doc fix :)

2023-01-04 15:49 UTC, Kerollmops commented on meilisearch/src/option.rs
> +// This means that the number of indexes is limited to about 200 for Linux, and about 20 for Windows.
```suggestion
// Each environment (index and task-db) is taking space in the virtual address space.
//
// The size of the virtual address space is limited by the OS. About 100TB for Linux and about 10TB for Windows.
// This means that the number of indexes is limited to about 200 for Linux and about 20 for Windows.
```

2023-01-04 15:55 UTC, Kerollmops approved these changes
Nice, thank you 🏝️
bors merge

2023-01-04 16:24 UTC, dureuill commented
fixed the merge conflict

2023-01-04 16:26 UTC, Kerollmops approved these changes
Haha, ok, nice 🤖
bors merge

2023-01-04 17:05 UTC, merged