Transparently resize indexes on MaxDatabaseSizeReached errors
meilisearch/meilisearch pull request #3319
Opened 2023-01-10 10:03 UTC by dureuill

# Pull Request

## Related issue
Related to https://github.com/meilisearch/meilisearch/discussions/3280, depends on https://github.com/meilisearch/milli/pull/760

## What does this PR do?

### User standpoint

- Meilisearch no longer fails tasks that encounter the `milli::UserError(MaxDatabaseSizeReached)` error.
- Instead, these tasks are retried after increasing the maximum size allocated to the index where the failure occurred.

### Implementation standpoint

- Add `Batch::index_uid` to get the `index_uid` of a batch of task if there is one
- `IndexMapper::create_or_open_index` now takes an additional `size` argument that allows to (re)open indexes with a size different from the base `IndexScheduler::index_size` field
- `IndexScheduler::tick` now returns a `Result<TickOutcome>` instead of a `Result<usize>`. This offers more explicit control over what the behavior should be wrt the next tick.
- Add `IndexStatus::BeingResized` that contains a handle that a thread can use to await for the resize operation to complete and the index to be available again.
- Add `IndexMapper::resize_index` to increase the size of an index.
- In `IndexScheduler::tick`, intercept task batches that failed due to `MaxDatabaseSizeReached` and resize the index that caused the error, then request a new tick that will eventually handle the still enqueued task.

## Testing the PR

The following diff can be applied to this branch to make testing the PR easier:

<details>

```diff
diff --git a/index-scheduler/src/index_mapper.rs b/index-scheduler/src/index_mapper.rs
index 553ab45a..022b2f00 100644
--- a/index-scheduler/src/index_mapper.rs
+++ b/index-scheduler/src/index_mapper.rs
@@ -228,13 +228,15 @@ impl IndexMapper {
 
         drop(lock);
 
+        std::thread::sleep_ms(2000);
+
         let current_size = index.map_size()?;
         let closing_event = index.prepare_for_closing();
-        log::info!("Resizing index {} from {} to {} bytes", name, current_size, current_size * 2);
+        log::error!("Resizing index {} from {} to {} bytes", name, current_size, current_size * 2);
 
         closing_event.wait();
 
-        log::info!("Resized index {} from {} to {} bytes", name, current_size, current_size * 2);
+        log::error!("Resized index {} from {} to {} bytes", name, current_size, current_size * 2);
 
         let index_path = self.base_path.join(uuid.to_string());
         let index = self.create_or_open_index(&index_path, None, 2 * current_size)?;
@@ -268,8 +270,10 @@ impl IndexMapper {
             match index {
                 Some(Available(index)) => break index,
                 Some(BeingResized(ref resize_operation)) => {
+                    log::error!("waiting for resize end");
                     // Deadlock: no lock taken while doing this operation.
                     resize_operation.wait();
+                    log::error!("trying our luck again!");
                     continue;
                 }
                 Some(BeingDeleted) => return Err(Error::IndexNotFound(name.to_string())),
diff --git a/index-scheduler/src/lib.rs b/index-scheduler/src/lib.rs
index 11b17d05..242dc095 100644
--- a/index-scheduler/src/lib.rs
+++ b/index-scheduler/src/lib.rs
@@ -908,6 +908,7 @@ impl IndexScheduler {
     ///
     /// Returns the number of processed tasks.
     fn tick(&self) -> Result<TickOutcome> {
+        log::error!("ticking!");
         #[cfg(test)]
         {
             *self.run_loop_iteration.write().unwrap() += 1;
diff --git a/meilisearch/src/main.rs b/meilisearch/src/main.rs
index 050c825a..63f312f6 100644
--- a/meilisearch/src/main.rs
+++ b/meilisearch/src/main.rs
@@ -25,7 +25,7 @@ fn setup(opt: &Opt) -> anyhow::Result<()> {
 
 #[actix_web::main]
 async fn main() -> anyhow::Result<()> {
-    let (opt, config_read_from) = Opt::try_build()?;
+    let (mut opt, config_read_from) = Opt::try_build()?;
 
     setup(&opt)?;
 
@@ -56,6 +56,8 @@ We generated a secure master key for you (you can safely copy this token):
         _ => (),
     }
 
+    opt.max_index_size = byte_unit::Byte::from_str("1MB").unwrap();
+
     let (index_scheduler, auth_controller) = setup_meilisearch(&opt)?;
 
     #[cfg(all(not(debug_assertions), feature = "analytics"))]
```
</details>

Mainly, these debug changes do the following:

- Set the default index size to 1MiB so that index resizes are initially frequent
- Turn some logs from info to error so that they can be displayed with `--log-level ERROR` (hiding the other infos)
- Add a long sleep between the beginning and the end of the resize so that we can observe the `BeingResized` index status (otherwise it would never come up in my tests)

## Open questions

- Is the growth factor of x2 the correct solution? For a `Vec` in memory it makes sense, but here we're manipulating quantities that are potentially in the order of 500GiBs. For bigger indexes it may make more sense to add at most e.g. 100GiB on each resize operation, avoiding big steps like 500GiB -> 1TiB.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-01-10 13:01 UTC, Kerollmops requested changes
I love your PR. I did a first review of it but will continue after you made your changes :)

2023-01-10 13:01 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +        };
I just find this part a little bit complex, I don't know if we can simplify it 🤔

2023-01-10 13:06 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +        };
Deletion operations are synchronous and therefore some match cases seems useless / dead code :)

2023-01-10 15:02 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +                let index = self.create_or_open_index(&index_path, date, self.index_size)?;
As we are opening the index, I'm not sure how we could preventively get its `map_size`.

LMDB allows passing 0, which would probably work, except maybe for new indexes we create?

2023-01-10 15:26 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
>                      panic!("Uuid v4 conflict.");
done

2023-01-10 15:26 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +        let current_size = index.map_size()?;
done

2023-01-10 15:26 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +        log::info!("Resizing index {} from {} to {} bytes", name, current_size, current_size * 2);
done, also changed the log level to debug

2023-01-10 15:27 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +        closing_event.wait();
switched to `wait_timeout`, I'm concerned that maybe I should put back the index in a consistent state (like "Available") in the in memory map though

2023-01-10 15:28 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +            }
>  Or will it be ugly?

Done. It is beautiful

2023-01-10 15:28 UTC, dureuill commented on index-scheduler/src/index_mapper.rs
> +                }
True, do you want me to add some more comments about this?

2023-01-10 16:42 UTC, dureuill commented
Pushed an update to handle the case where an error (eg IoError) would leave the hashmap in an inconsistent state.

2023-01-30 09:30 UTC, dureuill commented
I feel that with the tests I did, and the that that milli is now in main, this PR is now ready for review.

2023-02-07 14:08 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +                let index = self.create_or_open_index(&index_path, date, self.index_size)?;
LMDB's default map size is 1 MiB, couldn't we keep this constant value for when we open it? I mean instead of passing this `self.index_size`?

2023-02-07 14:13 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +        closing_event.wait();
If you take too much time to close the environment, what does it mean? That there potentially is a search running on the index?

2023-02-07 14:20 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +                }
Yes, please. Just for us to be able to understand, later that this is a possible issue.

2023-02-07 14:34 UTC, Kerollmops requested changes
As we merged milli into this repository on main recently, could you please rebase?

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +    /// This operation involves closing the underlying environment and so can take a long time to complete.
Can you add one of the main reasons why it can take time, which is: search requests are running and must stop before we can close it, please?

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +            }
I am sad that those two `panic`s can't be written on a single line.

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +            }
Also, note that those two panics will poison the lock. Is it ok?

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +                                };
Could you please use the `if let else` syntax here, as GitHub doesn't properly support this new syntax for highlighting, please?

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/index_mapper.rs
> +                                };
(And the second block is badly formatted too, due to a bad support of the new syntax too)

2023-02-07 14:34 UTC, Kerollmops commented on index-scheduler/src/lib.rs
> +}
I love this new enum 😍

2023-02-13 16:58 UTC, irevoire reviewed
Looks good to me.

Do you think there is a way to test this behaviour, though?
If we start at 1GiB, I think it'll be hard to do it, but maybe we could reduce this value to a few hundred bytes in the tests to ensure it effectively works wdyt?

2023-02-14 08:09 UTC, dureuill commented
> Do you think there is a way to test this behaviour, though?

It should really be in this PR, but #3331 adds automatic tests of index resizing.

2023-02-20 14:48 UTC, Kerollmops approved these changes
This is amazing. Thank you, merging!
bors merge

2023-02-20 15:42 UTC, merged