Csv delimiter
meilisearch/meilisearch pull request #3505
Opened 2023-02-16 13:45 UTC by irevoire

Fixes https://github.com/meilisearch/meilisearch/issues/3442
Closes https://github.com/meilisearch/meilisearch/pull/2803

This PR is a reimplementation of https://github.com/meilisearch/meilisearch/pull/2803, on the new engine. Thanks for your idea and initial PR @MixusMinimax; sorry I couldn’t update/merge your PR. Way too many changes happened on the engine in the meantime.

-------

It introduces four new error messages;
- Invalid value in parameter csvDelimiter: expected a string of one character, but found an empty string
- Invalid value in parameter csvDelimiter: expected a string of one character, but found the following string of 5 characters: doggo
- csv delimiter must be an ascii character. Found: 🍰 
- The Content-Type application/json does not support the use of a csv delimiter. The csv delimiter can only be used with the Content-Type text/csv.

And one error code;
- `invalid_index_csv_delimiter`

The `invalid_content_type` error code is now also used when we encounter the `csvDelimiter` query parameter with a non-csv content type.

2023-02-16 14:23 UTC, MixusMinimax commented
Thank you for implementing this, looks good! I think this will be very useful, as the csv standard is all over the place...
I'm not sure if even more configuration makes sense, there is a lot in csv:
https://docs.rs/csv/latest/csv/tutorial/index.html#delimiters-quotes-and-variable-length-records
But I think the delimiter is pretty much the only thing that is very frequently different.

2023-02-16 16:34 UTC, irevoire commented
> Thank you very much @irevoire. You could probably [co-sign the main commit](https://docs.github.com/fr/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) with @MixusMinimax's email 😊

Good idea! Will do 😁 

>  I'm not sure if even more configuration makes sense, there is a lot in csv:

Bad idea, please everyone, stop using custom-everything for a standard that is well defined and doesn't use any of these shenanigans 😂

2023-02-16 16:46 UTC, MixusMinimax commented
> Bad idea, please everyone, stop using custom-everything for a standard that is well defined and doesn't use any of these shenanigans

Hi, if I created my own data, I would totally agree, but in the real world you often have to deal with data sent to you by your customers or public databases. We're talking about csv datasets that are thousands of lines, and no, csv is not a well defined standard 😅

2023-02-20 13:30 UTC, Kerollmops requested changes
Thank you very much for the tests too!
Can you change the small change request I asked for, please?

2023-02-20 13:30 UTC, Kerollmops commented on meilisearch-types/src/document_formats.rs
> +    Csv(u8),
Can we change this to be a struct with a named field i.e. `delimiter`, please? That would be better.

2023-02-20 14:49 UTC, Kerollmops approved these changes
Thank you very much! I like what you've done here!
I approve that!

2023-02-20 17:01 UTC, irevoire commented
Thanks,
bors merge

2023-02-20 17:38 UTC, merged