Add scheduled test to Actions for all features
meilisearch/meilisearch pull request #3510
Opened 2023-02-18 15:29 UTC by jlucktay

# Pull Request

## Related issue

Fixes #3506.

## What does this PR do?

Add a new job to the Rust workflow to run `cargo build` and `cargo test` (on the cron schedule only) with the `--all-features` flag.
This will execute across all three environments: Linux, macOS, Windows.
    
Autoformat the Rust workflow file via [the Red Hat YAML extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).
This straightens out whitespace and string quoting for safer parsing.

As [pointed out by @irevoire here](https://github.com/meilisearch/meilisearch/issues/3506#issuecomment-1433501867), changes to CI such as this one will need to wait for #3496 before going ahead.
The new action [was executed on my fork](https://github.com/jlucktay/meilisearch/actions/runs/4211694210) but ended up failing on some metrics tests, as called out in that linked comment.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-03-02 17:31 UTC, curquiza requested changes
Hello @jlucktay 

Thanks a lot for the PR! Small changes needed
- can you only test this on Ubuntu (not windows and macOS) like we do in `test-linux` job? We use an Ubuntu container and not the native `ubuntu-18.04` of GitHub Action that will be soon deprecated
- can you remove the empty line between each step of the job you added?

2023-03-02 17:31 UTC, curquiza commented on .github/workflows/rust.yml
> +    - cron: "0 5 * * *"
can you remove this change please? 😊

2023-03-06 09:50 UTC, curquiza requested changes
Hello @jlucktay 

Are you sure your CI is working, have you done any manual test?

Because I don't see the following steps in your jobs:

```yml
- name: Install needed dependencies
        run: |
          apt-get update && apt-get install -y curl
          apt-get install build-essential -y
- uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
```

And they are in the other jobs using the ubuntu-18.04 Docker image

2023-03-06 12:47 UTC, jlucktay commented
> Hello @jlucktay
> 
> Are you sure your CI is working, have you done any manual test?
> 
> Because I don't see the following steps in your jobs:
> 
> ```yaml
> - name: Install needed dependencies
>         run: |
>           apt-get update && apt-get install -y curl
>           apt-get install build-essential -y
> - uses: actions-rs/toolchain@v1
>         with:
>           toolchain: stable
>           override: true
> ```
> 
> And they are in the other jobs using the ubuntu-18.04 Docker image

I triggered some runs on my fork about two weeks ago before I opened the PR, yes.

The [Actions runner images come with Rust, curl, and the build-essential package installed already](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md), so those extra two steps do seem redundant, but I have included them now anyway.

I have just run [another fresh round of tests](https://github.com/jlucktay/meilisearch/actions/runs/4343243448/jobs/7585049782) now.

2023-03-06 13:32 UTC, curquiza commented
> I triggered some runs on my fork about two weeks ago before I opened the PR, yes.

Yes so you tested 2 weeks ago with `ubuntu-18.04` provided by GitHub and not the changes I asked with the docker image ubuntu-18.04. Because it does not work without these 2 steps 😊 

Thanks for the changes, I review this now

2023-03-06 14:57 UTC, curquiza commented
bors merge

2023-03-06 16:44 UTC, merged