Added a cron test for disabled all-tokenization
meilisearch/meilisearch pull request #3746
Opened 2023-05-11 20:33 UTC by roy9495

# Pull Request

## Related issue
Fixes #3743

## What does this PR do?
- This  cron test checks if  all-tokenization is disabled or not

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-05-15 16:21 UTC, curquiza requested changes
Hello!
thank you for the PR

you have to add this missing step

```yml
- uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
```

otherwise the command with `cargo` will not work

2023-05-15 18:07 UTC, roy9495 commented
I updated the cron job . But now there are two commits . Do you want me to squash them?

2023-05-16 12:49 UTC, curquiza commented
No that's ok @roy9495, no need to squash. Thank you for your reactivity

2023-05-16 12:50 UTC, curquiza commented on .github/workflows/test-suite.yml
> +      - name: Run cargo tree without default features
```suggestion
      - name: Run cargo tree without default features and check lindera is not present
```

2023-05-16 12:50 UTC, curquiza commented on .github/workflows/test-suite.yml
> +      - name: Run cargo tree with default features
```suggestion
      - name: Run cargo tree with default features and check lindera is pressent
```

2023-05-16 12:51 UTC, curquiza commented on .github/workflows/test-suite.yml
> +    name: Test Disabled Tokenization
```suggestion
    name: Test disabled tokenization
```

2023-05-16 12:52 UTC, curquiza approved these changes
Thanks again @roy9495 for the PR

bors merge

2023-05-23 10:08 UTC, curquiza commented
bors merge-

2023-05-23 10:08 UTC, curquiza commented
bors merge

2023-05-23 14:57 UTC, curquiza commented
bors help

2023-05-24 08:59 UTC, curquiza commented
Hello @roy9495 
I'm sorry, I don't know why, there is an issue with our merging tool. It says the branch does not exist, but I can see your branch on your forked repository so I really don't understand.

Can you help us and squash the commits? 🙏 
I will try to merge again, and if it does not work I will cherry-pick this only commit into a new branch and merge it.

Thank you in advance

2023-05-24 17:50 UTC, roy9495 commented
Certainly, I will be sure to do that.

2023-05-24 18:19 UTC, roy9495 commented
Sorry for the delay

2023-05-25 07:58 UTC, curquiza commented
bors try

2023-05-25 08:00 UTC, curquiza commented
bors try-

2023-05-25 08:02 UTC, curquiza commented on .github/workflows/test-suite.yml
> +    name: Test Disabled Tokenization
```suggestion
    name: Test disabled tokenization
```

2023-05-25 08:03 UTC, curquiza commented on .github/workflows/test-suite.yml
> +      - name: Run cargo tree without default features
```suggestion
      - name: Run cargo tree without default features and check lindera is not present
```

2023-05-25 08:03 UTC, curquiza commented on .github/workflows/test-suite.yml
> +      - name: Run cargo tree without default features
```suggestion
      - name: Run cargo tree without default features and check lindera is not present
```

2023-05-25 08:04 UTC, curquiza commented on .github/workflows/test-suite.yml
> +      - name: Run cargo tree with default features
```suggestion
      - name: Run cargo tree with default features and check lindera is pressent
```

2023-05-25 08:05 UTC, curquiza approved these changes
bors merge

2023-05-25 09:44 UTC, curquiza commented
Sorry I don't know why it still does not work.

Replaced by https://github.com/meilisearch/meilisearch/pull/3779

@roy9495, I cherry-picked your commits, so you will still be a contributor of Meilisearch 😄

2023-05-25 09:44 UTC, closed without merging

2023-05-25 10:11 UTC, roy9495 commented
Thank you

2023-05-25 14:42 UTC, curquiza commented
Thank you for your work and time ❤️