Define searchable fields at runtime
meilisearch/meilisearch pull request #3834
Opened 2023-06-13 15:42 UTC by ManyTheFish

TBD @ManyTheFish

2023-06-20 15:42 UTC, Kerollmops requested changes
Thank you for your work!

If I understand correctly now, you store a `Cow<'ctx, [u8]>` instead of an `&'ctx [u8]` because you fetch multiple keys from different databases (that are CBO-encoded) and merge them with the `merge_cbo_roaring_bitmaps` function (which gives you a `Cow<'ctx, [u8]>`). You store that in the cache and deserialize the data from the raw bytes (like before).

If I am right, there is now the thing that I don't quite like: the previous version kept the `&'ctx [u8]` because it was a pointer in the LMDB database, so there was nearly nothing to keep in memory at the expense of a deserialization cost. However, storing a `Cow<'ctx, [u8]>::Owned` (so a `Vec<u8>`) isn't interesting. I prefer that we change the type to something like a `Either<&'ctx [u8], RoaringBitmap>` instead.

Additionally, I don't know if we can eliminate the new `BytesDecodeOwned` trait you introduced. I know we talked a bit about it, but maybe we can ask the help of @dureuill. Can't we just for it like: `DC::DItem + 'static`? This way, we are sure that the deserialized data doesn't depend on any lifetime for the DB.

2023-06-20 15:42 UTC, Kerollmops commented on milli/src/search/new/mod.rs
> +        self.restricted_fids = Some(restricted_fids);
```suggestion
        self.restricted_fids =
            Some(searchable_attributes.iter().filter_map(|name| fids_map.id(name)).collect());
```

2023-06-20 15:42 UTC, Kerollmops commented on milli/src/search/new/db_cache.rs
> +            Entry::Occupied(_) => {}
```suggestion
            Entry::Occupied(_) => (),
```

2023-06-20 15:42 UTC, Kerollmops commented on milli/src/search/new/db_cache.rs
> +            Entry::Occupied(_) => {}
```suggestion
            Entry::Occupied(_) => (),
```

2023-06-21 07:47 UTC, ManyTheFish commented
Hello @Kerollmops,
Thank you for your suggestions, after some tries, making the changes you suggested are not as trivial as I expected.
I propose to continue this work in a dedicated PR and merge this one.
Obviously, I will work on this this week. What do you think? Do you see any blockers to this? 😄

2023-06-21 07:57 UTC, Kerollmops commented
Hey @ManyTheFish,

You are right, let's merge this right now. I am impressed of the low number of code needed for the logic of the feature. I hope you find a way to improve the cache system for owned value next week 🤞

Bors merge

2023-06-21 08:25 UTC, dureuill commented
Could we consider rewriting the tests to use `insta` instead of `assert_eq`? it makes the experience of modifying the tests later if needed much smoother

2023-06-21 08:55 UTC, Kerollmops commented
> Could we consider rewriting the tests to use `insta` instead of `assert_eq`? it makes the experience of modifying the tests later if needed much smoother

That's a good idea. @ManyTheFish Could you do that, I'm pretty sure it will not take a lot of time ;)

2023-06-21 10:13 UTC, ManyTheFish commented
@Kerollmops @dureuill, yup! no problem!

2023-06-28 08:19 UTC, Kerollmops approved these changes
Looks perfect to me, thank you 🐝
bors merge

2023-06-28 08:52 UTC, merged