Revamp analytics
meilisearch/meilisearch pull request #5011
Opened 2024-10-17 08:39 UTC by irevoire

# Pull Request

## Related issue
Fixes https://github.com/meilisearch/meilisearch/issues/5009

## What does this PR do?
- ...

2024-10-17 13:46 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +    total_received: usize,
default of `usize` is `0` so aggregation may always return `0`

2024-10-17 13:49 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +#[derive(Default, Serialize)]
We may prefer avoid the `Default` impl, too error prone.
```suggestion
#[derive(Serialize)]
```

2024-10-17 13:50 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +    total_received: usize,
Is `total_received` necessary here?

2024-10-17 13:54 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +#[derive(Default, Serialize)]
```suggestion
#[derive(Serialize)]
```

2024-10-17 13:55 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +#[derive(Default, Serialize)]
```suggestion
#[derive(Serialize)]
```

2024-10-17 13:57 UTC, ManyTheFish commented on meilisearch/src/routes/indexes/documents.rs
> +#[derive(Default, Serialize)]
```suggestion
#[derive(Serialize)]
```

2024-10-17 15:22 UTC, ManyTheFish requested changes
Some changes before the WE, sorry :/

2024-10-19 07:17 UTC, irevoire commented
I think I messed up the settings. When I started using the or instead of the map_or stuff, I should have swapped the order of the self and other field to select the new one instead of the old one.

+ I want to rename the argument of the aggregate function trait to call it "new" instead of "other" so it's clearer which version is new and old

2024-10-20 15:21 UTC, irevoire commented
I don’t think we need to integrate the helper function into the trait, we can simply specialize it at compile time and get a ptr to it without putting it in the trait

2024-10-21 15:50 UTC, merged