Attach index name in error message
meilisearch/meilisearch pull request #5056
Opened 2024-11-14 09:09 UTC by airycanon

# Pull Request

## Related issue
Fixes #4392 

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-11-18 03:45 UTC, airycanon commented
@irevoire could you please take a look at this PR?

2024-11-27 06:32 UTC, airycanon commented
kindly ping @irevoire

2024-11-27 08:40 UTC, Kerollmops commented
Hey @airycanon 👋

@irevoire is on vacation and will come back next week. He will dedicate some time to review your PR soon.

Thank you for your contribution 😊

2024-12-05 15:13 UTC, irevoire requested changes
Hey, the implementation looks really good!
I think we'll be able to merge this PR in no time, thanks a lot and sorry for the delay :pray: 

I left a few comments here and there, but nothing hard to fix.
And could you rebase on the `release-v1.12` branch because that's definitely something I would like to have for the next release.
I'll update the base branch on github directly.

2024-12-05 15:13 UTC, irevoire commented on crates/index-scheduler/src/batch.rs
> +                        .map_err(|e| Error::from_milli(e, Some(uuid.to_string())))?;
```suggestion
                        .map_err(|e| Error::from_milli(e, Some(name.to_string())))?;
```

here it's the name of the index that we want to return

2024-12-05 18:19 UTC, airycanon commented
@irevoire Thanks for you guidance, I've addressed all the comments in this PR. Could you please take another look?

2024-12-09 09:58 UTC, irevoire approved these changes
Hey @airycanon,

Looks awesome! Thanks for your PR 🫶 
Merging
bors merge

2024-12-09 10:40 UTC, merged