Split Meilisearch Crate Tests in separate file
meilisearch/meilisearch pull request #5134
Opened 2024-12-07 19:07 UTC by K-Kumar-01

# Pull Request
Splits the tests for meilisearch crate in a separate file.

## Related issue
Fixes #5116 

## What does this PR do?
- Splits the test for `/indexes/search.rs` into a separate file `indexes/search_test.rs` in meilisearch crate

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-12-07 19:14 UTC, K-Kumar-01 commented
@irevoire @curquiza 
I am Kushal. I came across Meilisearch and was looking to contribute to the organization. I looked at the good-first issues and found an issue to split unit tests into separate test files. Since I am new to Rust, I thought I would be able to familiarize myself with the codebase and feel comfortable with Rust while working on the issue.
I tried creating a draft PR for one of the files present in meilisearch crate.
Could you guys take a look at the PR and let me know your thoughts?

Thanks :smile: 
Kushal

2024-12-09 09:51 UTC, irevoire requested changes
Hey @K-Kumar-01, we’re almost good.
Only one easy comment and we’ll be good to merge, thanks for your contribution!

2024-12-09 09:51 UTC, irevoire commented on crates/meilisearch/src/routes/indexes/search_test.rs
> +pub mod search_test {
Here it would be better to remove this block and instead put the cfg(test) while importing the file

2024-12-09 09:51 UTC, irevoire commented on crates/meilisearch/src/routes/indexes/mod.rs
> +mod search_test;
```suggestion
#[cfg(test)]
mod search_test;
```

2024-12-16 15:04 UTC, irevoire approved these changes
Hey, sorry I pushed on your branch to fix the few remaining broken things.
Thanks for your contribution

bors merge

2024-12-16 16:06 UTC, merged

2024-12-16 21:38 UTC, K-Kumar-01 commented
> Hey, sorry I pushed on your branch to fix the few remaining broken things. Thanks for your contribution
> 
> bors merge

No worries @irevoire 
Thanks for the fix.