Offline upgrade v1.12
meilisearch/meilisearch pull request #5146
Opened 2024-12-10 14:14 UTC by ManyTheFish

# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- add v1_11_to_v1_12 function to upgrade Meilisearch from v1.11 to v1.12
- Convert the update files from OBKV to ndjson format

2024-12-10 15:09 UTC, Kerollmops requested changes
Would it be possible to add much more `.context` uses, like on every `?`, please? The thing is that we are doing a lot of file operations and they never display the file names on errors. I recommend using `with_context(|| format!("while ... on {:?}", file.display))?`.

2024-12-11 09:46 UTC, Kerollmops requested changes
It looks much better to me, thank you 🧑‍🍳
However, can you clean up the commits, please?

2024-12-11 09:58 UTC, Kerollmops submitted a review, later dismissed
Love it. Thank you 👍
bors merge

2024-12-11 10:42 UTC, dureuill commented on crates/meilitool/src/upgrade/v1_12.rs
> +            .persist(&update_file_path)
```suggestion
            // replace the obkv file with the rewritten NDJSON file
            .persist(&update_file_path)
```

2024-12-11 10:43 UTC, dureuill commented
I added a clarification comment

2024-12-11 13:36 UTC, irevoire approved these changes
-> The general process seems good to me
-> Arroy didn't change
-> The index-scheduler works with the new batches route :tada: 
Thanks @ManyTheFish :fire: 

bors merge

2024-12-11 14:15 UTC, merged