Ensure the settings routes are now configurated when a new field is added to the Settings struct
meilisearch/meilisearch pull request #5149
Opened 2024-12-11 06:48 UTC by MichaScant

# Pull Request
## Related issue
Fixes #5126 

## What does this PR do?
Ensures the settings routes are properly configured before a new field is added to the settings structure. Changes were made based on what was proposed in the original issue, any new field for settings struct is added in the [make_settings_route! macro list](https://github.com/meilisearch/meilisearch/blob/6298db5bea845fae7937c4b3476fd1cf5e7af9ee/crates/meilisearch/src/routes/indexes/settings.rs#L182-L403) 

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-12-12 08:59 UTC, ManyTheFish requested changes
Hey @MichaScant, your code is actually testing if the listed settings are in the `Settings` struct, however, this case is already ensured at compile time.
What I want is to check the invert, ensure that all the settings in the struct are listed in this macro.

I suggest to decompose the structure using the listed settings like:
```rust
meilisearch_types::settings::Settings { $($attr: _),*} = meilisearch_types::settings::Settings::default();
```

But to make this work you must start your work from the `release-v1.12.0` branch instead of `main` the code is different between the 2 branches

2024-12-13 14:50 UTC, MichaScant commented
> Hey @MichaScant, your code is actually testing if the listed settings are in the `Settings` struct, however, this case is already ensured at compile time. What I want is to check the invert, ensure that all the settings in the struct are listed in this macro.
> 
> I suggest to decompose the structure using the listed settings like:
> 
> ```rust
> meilisearch_types::settings::Settings { $($attr: _),*} = meilisearch_types::settings::Settings::default();
> ```
> 
> But to make this work you must start your work from the `release-v1.12.0` branch instead of `main` the code is different between the 2 branches

2024-12-13 14:54 UTC, MichaScant commented
> Hey @MichaScant, your code is actually testing if the listed settings are in the `Settings` struct, however, this case is already ensured at compile time. What I want is to check the invert, ensure that all the settings in the struct are listed in this macro.
> 
> I suggest to decompose the structure using the listed settings like:
> 
> ```rust
> meilisearch_types::settings::Settings { $($attr: _),*} = meilisearch_types::settings::Settings::default();
> ```
> 
> But to make this work you must start your work from the `release-v1.12.0` branch instead of `main` the code is different between the 2 branches

Ok thank you, I will get started on that right away, to clarify, I would then be merging my code into release-v1.12.0 rather than main in that case right?

2024-12-16 08:39 UTC, dureuill commented
> I  would then be merging my code into release-v1.12.0 rather than main, right?

Yes exactly :+1:

2024-12-19 09:46 UTC, curquiza commented
@MichaScant can you fix the tests (CI) please?

Thank you again for your PR

2024-12-20 21:29 UTC, MichaScant commented
> @MichaScant can you fix the tests (CI) please?
> 
> Thank you again for your PR

fixed

2025-01-07 08:56 UTC, ManyTheFish reviewed
Hello @MichaScant,

Thank you for your PR.
However, it doesn't fit the needs, I let you read my changed request comment, and if you have any question don't hesitate to ask them.
Sorry to ask this, but time passed and the release v1.12.0 has been merged in `main`, could you rebase again? 🙏

2025-01-07 08:56 UTC, ManyTheFish commented on crates/meilisearch/src/routes/indexes/settings.rs
> +x
```suggestion
```

2025-01-07 08:56 UTC, ManyTheFish commented on crates/meilisearch/src/routes/indexes/settings.rs
> +
```suggestion
```

2025-01-07 08:56 UTC, ManyTheFish commented on crates/meilisearch/src/routes/indexes/settings.rs
> +            }
This doesn't fit the needs. Here, you are checking if the `meilisearch_types::settings::Settings` contains the provided setting, however that's not what I wanted, I wanted to ensure that every setting contained in the `meilisearch_types::settings::Settings` struct are specified in the `make_setting_routes` macro.

This function should be moved in the `make_setting_routes` (plural) macro (upper) instead of `make_setting_route` and the `Settings` struct should be exhaustively destructured (if it ends by `, .. }` it's wrong).

2025-01-09 10:35 UTC, ManyTheFish commented
Hey @MichaScant,
Thank you for the changes,
However, the test CI doesn't pass. Can you fix them before we can review your PR again, please? 😄

`cargo test --locked --release --all` is the failing command run by the CI.

I converted the PR to a draft; you can put it back as RFR when ready. This will let us know when we can review it.

Thank you!

2025-01-16 19:44 UTC, MichaScant commented
Hey sorry about that, tests cases are passing now on my end

2025-02-03 10:57 UTC, ManyTheFish commented on crates/meilisearch/src/routes/indexes/settings.rs
> +                    let meilisearch_types::settings::Settings { $($attr: _,)* .. }:
Hey @MichaScant, sorry for the delay, but, isn't it possible t remove the below `..`?
```suggestion
                    let meilisearch_types::settings::Settings { $($attr: _,)* }:
```

If we keep it, it will allow an addition in the settings struct that is not listed by this macro. 🤔

2025-02-03 21:49 UTC, MichaScant commented on crates/meilisearch/src/routes/indexes/settings.rs
> +                    let meilisearch_types::settings::Settings { $($attr: _,)* .. }:
I can however this would cause cargo test --locked --release --all to fail, as it is causing the following error: pattern requires `..` due to inaccessible fields.

I can get around this by using kind: _ , if that would work: 
let meilisearch_types::settings::Settings { $($attr: _,)* _kind: _ }:

2025-02-04 08:44 UTC, ManyTheFish commented on crates/meilisearch/src/routes/indexes/settings.rs
> +                    let meilisearch_types::settings::Settings { $($attr: _,)* .. }:
Yes you can try this, the goal is to ensure that a field added to the Settings is never forgotten in this macro, that's why we can't allow `..` 🤔

2025-02-06 09:12 UTC, ManyTheFish submitted a review, later dismissed
Look great to me!

Thank you a lot @MichaScant for your contribution,

let's try to merge it! :) 

bors merge

2025-02-06 09:14 UTC, ManyTheFish commented
@MichaScant, 
The last change to make for you is to make the CI happy; the Rustfmt is not passing; can you install and run it?

2025-02-06 15:05 UTC, MichaScant commented
fixed the rustfmt issue, however in regards to the Windows test suite, I don't see how the failure their is related to my issue, could you please confirm?

2025-02-10 11:47 UTC, curquiza commented
Hello @MichaScant 
Our Windows CI is flaky unfortunately, it's probably not related to your PR and I think we can merge it without that. I let @ManyTheFish do the final review

2025-02-11 09:00 UTC, ManyTheFish approved these changes
Let's try,

bors merge

2025-02-11 20:10 UTC, curquiza commented
bors merge

2025-02-11 20:46 UTC, merged