fix backups
meilisearch/MeiliSearch pull request #982
Opened 2020-09-29 11:41 UTC by LegendreM

* pluralize variable `backup_folder` -> `backups_folder`
* change env case `MEILI_backup_folder` -> `MEILI_BACKUPS_FOLDER`
* add miliseconds to backup ID to reduce colisions

2020-09-29 15:30 UTC, curquiza requested changes
You changed the `movies.json` file when changing backup into dump 😉

2020-09-29 16:46 UTC, MarinPostma requested changes

2020-09-29 16:46 UTC, MarinPostma commented on meilisearch-http/src/dump.rs
> +    eprintln!("Import dump from {:?}", dump_path);
can you use the macros from the log crate instead? (log, warn etc...)

2020-09-29 16:46 UTC, MarinPostma commented on meilisearch-http/src/dump.rs
> +    eprintln!("Dump importation from {:?} succeed", dump_path);
same here

2020-09-29 16:46 UTC, MarinPostma commented on meilisearch-http/src/dump.rs
> +    eprintln!("Import dump from {:?}", dump_path);
```suggestion
    eprintln!("Importing dump from {:?}...", dump_path);
```

2020-09-29 16:46 UTC, MarinPostma commented on meilisearch-http/tests/dump.rs
>      println!("{:?}", value);
oops debug message

2020-09-30 09:52 UTC, MarinPostma approved these changes
can you squash everything in one commit please?

2020-09-30 17:02 UTC, MarinPostma commented
Bors merge

2020-09-30 17:28 UTC, merged